#!/bin/sh
# ESS[BUGS]:  02/18/2004
# runs BUGS taking commands from command file
#

case `config.guess` in
    i?86-pc-cygwin)     BUGS=bugs0603.exe;;
    i?86-*-linux*)      BUGS=bugs0600.linux;;
    sparc-sun-solaris*) BUGS=bugs603.sparc;;
    mips-sgi-irix*)     BUGS=bugs06.sgi;;
esac

case $# in
     1) $BUGS 32 bugs $1 2>> bugs.log
	cp -fp bugs.log bugs.bog
	chmod -w bugs.bog
	;;
     2) $BUGS 32 $1 $2 2>> $1.log
	cp -fp $1.log $1.bog
	chmod -w $1.bog
	;;
     3) $BUGS $1 $2 $3 2>> $2.log
	cp -fp $2.log $2.bog
	chmod -w $2.bog
	;;
     *) echo "usage: $0 [[number_of_bins] default_output_name] command_file";;
esac
