#!/bin/sh
# ESS[BUGS]:  02/18/2004
# runs BUGS taking commands from command file
#

if [ ${BUGS:?} = "BUGS: parameter null or not set" ]
then 
    case `config.guess` in
	alpha*-dec-*)       BUGS=bugs05.decalpha;;
        hppa*-hp-hpux*)     BUGS=bugs05.hp;;
	i?86-pc-cygwin)     BUGS=bugs05.exe;;
	i?86-*-freebsd*)    BUGS=bugs05.freebsd;;
	powerpc*-*-*)       BUGS=bugs05.rs6000;;
	sparc-sun-solaris*) BUGS=bugs05.sparc;;
	mips-sgi-irix*)     BUGS=bugs05.sgi;;
	mips-dec-*)         BUGS=bugs05.decmips;;
    esac
fi

case $# in
     1) $BUGS 32 bugs $1
	cp -fp bugs.log bugs.bog
	chmod -w bugs.bog
	;;
     2) $BUGS 32 $1 $2
	cp -fp $1.log $1.bog
	chmod -w $1.bog
	;;
     3) $BUGS $1 $2 $3
	cp -fp $2.log $2.bog
	chmod -w $2.bog
	;;
     *) echo "usage: $0 [[number_of_bins] default_output_name] command_file";;
esac
