#!/bin/sh

### (C) 1997, Richard M. Heiberger.
### This file is part of ESS.

## This file is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2, or (at your option)
## any later version.

## This file is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with GNU Emacs; see the file COPYING.  If not, write to
## the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

# For executing SAS, and running it in the proper manner for ESS
# (feeding output back into appropriate ESS buffers).

echo $0 $@
sas </dev/tty 1>$5 2>$6 $1 $2 $3 $4


