\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename announc.info
@settitle ESS - Emacs Speaks Statistics
@comment %**end of header

@include ess-defs.texi
@node Announce
@comment  node-name,  next,  previous,  up
@chapter ANNOUNCING ESS
@cindex ANNOUNCE

The ESS Developers proudly announce the release of ESS
@include ../VERSION

@c --------------------------------------------------------------------
Emacs Speaks Statistics (ESS) provides an intelligent, consistent
interface between the user and the software.  ESS interfaces with
R/S-PLUS, SAS, BUGS/JAGS, Stata and other statistical analysis
packages under the UNIX, GNU Linux, Microsoft Windows, Mac OS X and
other operating systems.  ESS is a package for the GNU Emacs and
XEmacs text editors whose features ESS uses to streamline the creation
and use of statistical software.  ESS knows the syntax and grammar of
statistical analysis packages and provides consistent display and
editing features based on that knowledge.  ESS assists in interactive
and batch execution of statements written in these statistical
analysis languages.

ESS is freely available under the GNU General Public License (GPL).
Please read the file COPYING which comes with the distribution, for
more information about the license. For more detailed information,
please read the README files that come with ESS.
@c And to clear up any possible confusion; the name is ESS, NOT ESS-mode.
@c Thank you :-).

@menu
* Latest Version::
* Current Features::
* Requirements::
* Stability::
* Mailing List::
* Reporting Bugs::
* Authors::
* License::
* New Features::
@end menu

@node Latest Version, Current Features, Announce, Announce
@section Getting the Latest Version
@include getting.texi

@node Current Features, Requirements, Latest Version, Announce
@section Current Features
@include currfeat.texi

@node Requirements, Stability, Current Features, Announce
@section Requirements
@include requires.texi

@node Stability, Mailing List, Requirements, Announce
@section Stability
@include stabilty.texi

@node Mailing List, Reporting Bugs, Stability, Announce
@section Mailing List
@include mailing.texi

@node Reporting Bugs, Authors, Mailing List, Announce
@section Reporting Bugs
@include bugrept.texi

@node Authors, License, Reporting Bugs, Announce
@section Authors
@include authors.texi

@node License, New Features, Authors, Announce
@section License
@include license.texi

@node New Features,  , License, Announce
@section New Features
@include newfeat.texi

@bye
@c Remember to delete these lines before creating the info file.
@iftex
@lucidbook
@bindingoffset = 0.5in
@parindent = 0pt
@end iftex

@comment Local Variables:
@comment TeX-master: "announc.texi"
@comment End:
