\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename readme.info
@settitle ESS - Emacs Speaks Statistics
@comment %**end of header

@include ess-defs.texi
@node General Information
@chapter General Information: README
@cindex README

This is the README file for the distribution of ESS version
@include ../VERSION

ESS is a GNU Emacs package for interactive statistical
programming and data analysis.  Languages supported: the S family (S,
S-PLUS and R), SAS, BUGS/JAGS and Stata.  ESS grew out of the
desire for bug fixes and extensions to S-mode and SAS-mode as well as a
consistent union of their features in one package.

Installation instructions are provided in sections for both Unix and
Windows; see below.

The current development team is led by Martin Maechler since August
2004. Former project leader A.J. (Tony) Rossini
(@email{rossini@@blindglobe.net}) did the initial port to XEmacs and has
been the primary coder.  Martin Maechler
(@email{maechler@@stat.math.ethz.ch}) and Kurt Hornik
(@email{Kurt.Hornik@@R-project.org}) have assisted with the S family and
XLispStat.  Stephen Eglen (@email{stephen@@gnu.org}) has worked mostly
on R support.  Richard M. Heiberger (@email{rmh@@temple.edu}) has
assisted with S/S-PLUS development for Windows.  Richard and Rodney
A. Sparapani (@email{rsparapa@@mcw.edu}) have done much of the work
improving SAS batch and interactive support.  Rodney has also
extended ESS to support BUGS/JAGS and has an interest in improving
Stata support.

We are grateful to the previous developers of S-mode (Doug Bates, Ed Kademan,
Frank Ritter, David M. Smith), SAS-mode (Tom Cook) and Stata-mode (Thomas
Lumley).
@c The name is ESS.  Not ESS-mode.

@ifplaintext
Table of Contents

@itemize @bullet
@item License
@item Stability
@item Requirements
@item Latest Version
@item Installation
@item Starting an ESS Process
@item New Features
@item Current Features
@item Reporting Bugs
@item Mailing Lists
@item Authors
@end itemize
@end ifplaintext

@menu
* License::
* Installation::
* Starting up::
* Current Features::
* New Features::
* Reporting Bugs::
* Mailing Lists::
* Authors::
@end menu

@node License, Installation, General Information, General Information
@section License
@include license.texi

@node Installation, Starting up, License, General Information
@section Installation
@include installation.texi

@node Starting up, Current Features, Installation, General Information
@section Starting an ESS process
To start an @Sl{} session on Unix or on Windows when you
use the Cygwin bash shell, simply type @kbd{M-x S RET}.

To start an @Sl{} session on Windows when you
use the MSDOS prompt shell, simply type @kbd{M-x S+6-msdos RET}.

@node Current Features, New Features, Starting up, General Information
@section Current Features

@include currfeat.texi

@node New Features, Reporting Bugs, Current Features, General Information
@section New Features

@include newfeat.texi

@node Reporting Bugs, Mailing Lists, New Features, General Information
@section Reporting Bugs

@include bugrept.texi

@node Mailing Lists, Authors, Reporting Bugs, General Information
@section Mailing Lists

@include mailing.texi

@node Authors,  , Mailing Lists, General Information
@section Authors

@include authors.texi

@bye
@c Remember to delete these lines before creating the info file.
@iftex
@lucidbook
@bindingoffset = 0.5in
@parindent = 0pt
@end iftex

@comment Local Variables:
@comment TeX-master: "readme.texi"
@comment End:
