\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename readme.info
@settitle ESS --- Comments on Microsoft/ESS Integration
@comment %**end of header
@comment $Id: README.Microsoft.texi,v 1.1 2000/06/29 18:35:08 rossini Exp $

@node General Installation and Use
@comment  node-name,  next,  previous,  up
@section Introduction

@include ms-inst.texi


@node S-PLUS use
@comment  node-name,  next,  previous,  up
@section S-PLUS use

@include help-sp.texi

@node SAS use
@comment  node-name,  next,  previous,  up
@section SAS use

@include help-sas.texi


@node Microsoft Specific Problems
@comment  node-name,  next,  previous,  up
@section Microsoft problems

@include bugs-ms.texi


@node S-PLUS Specific Problems
@comment  node-name,  next,  previous,  up
@section S-PLUS problems

@include bugs-s.texi


@node SAS Specific Problems
@comment  node-name,  next,  previous,  up
@section SAS-problems

@include bugs-sas.texi


@bye
@c Remember to delete these lines before creating the info file.
@iftex
@lucidbook
@bindingoffset = 0.5in
@parindent = 0pt
@end iftex

@comment Local Variables:
@comment TeX-master: "README.Microsoft.texi"
@comment End:
