#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/ess

# Written by Jim Van Zandt <jrv@vanzandt.mv.com>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=ess

if [ ${FLAVOR} = emacs ]; then exit 0; fi

if [ ${FLAVOR} = xemacs21 ]; then exit 0; fi

if [ ${FLAVOR} = emacs22 ]; then exit 0; fi

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

FLAVORTEST=`echo $FLAVOR | cut -c-6`
if [ ${FLAVORTEST} = xemacs ] ; then
    SITEFLAG="-no-site-file -no-init-file"
else
    SITEFLAG="--no-site-file --no-init-file"
fi
FLAGS="${SITEFLAG} -q -batch -l path.el -l ess-comp.el -f batch-byte-compile"
#FLAGS1="${SITEFLAG} -q -batch -l path.el -l ess-comp.el -l ess-vars.elc -f batch-byte-compile"

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}

# Install-info-altdir does not actually exist. 
# Maybe somebody will write it.
if test -x /usr/sbin/install-info-altdir; then
    echo install/${PACKAGE}: install Info links for ${FLAVOR}
    install-info-altdir --quiet --section "" "" --dirname=${FLAVOR} /usr/info/${PACKAGE}.info.gz
fi

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
FILES=$(ls -1 *.el | grep -vx 'ess.el')
## edd 08 Nov 2010 old code
#cp ${FILES} ess.el ${ELCDIR}
#cd ${ELCDIR}
## edd 08 Nov 2010 replaced by this (cf #594750)
cd ${ELCDIR}
for f in ${ELDIR}/*.el; do
    ln -sf $f .
done

cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
EOF
${FLAVOR} ${FLAGS} ${FILES}
${FLAVOR} ${FLAGS} ess.el
#rm -f *.el path.el

exit 0
